### ISSUE TITLE
这个地方链接失效直接卡死了

### ISSUE THREAD

**Issue by wulixiaoxiao** [webbc/laravelcms#2]
/**
     * 获取Ip地址所在的区域
     * @param $ip ip地址
     * @return string 区域
     */
    private static function getCityByIp($ip) {
        $url = "http://int.dpool.sina.com.cn/iplookup/iplookup.php?format=json&ip=" . $ip;
        $json = file_get_contents($url);
        if ($json == -1) {
            return '内网地址';
        } else if ($json == -2) {
            return 'ip地址有误';
        } else {
            $address = json_decode($json, true);
            return $address['country'] . $address['province'] . $address['city'];
        }
    }

**Comment by webbc** [comment]
获取IP这部分代码你可以先删除，或者找其他的API来替代
